core/urls.py
from django.contrib import admin
from django.urls import path
from ecomerce.views import index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from ecomerce.views import index, signup, UserViewSet
from item.serializer import CategorySerializer
from item.views import CategoryViewSet, ItemViewVset
from item.models import Category, Item

from ecomerce.views import UserViewSet
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         user = User
#         field = ('url', 'username', 'email', 'is_staff')
#
#
# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'category',CategoryViewSet, basename=Category)
router.register(r'items', ItemViewVset, basename=Item)
urlpatterns = router.urls
urlpatterns = [
                  path('', include('ecomerce.urls')),
                  path('api/', include(router.urls)),
                  path('admin/', admin.site.urls),
                  path('item/', include('item.urls')),
                  path('dashboard/', include('dashboard.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
from dashboard.views import index

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='dashboard')
]

ecomerce/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from django.urls import path, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
app_name = 'ecomerce'

urlpatterns = [
    path('',views.index, name = 'index'),
    path('signup/',views.signup, name='signup' ),
    path('login/', auth_views.LoginView.as_view(template_name='ecomerce/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

item/urls.py
from django.urls import path, include
from item.views import detail
from . import views
from . forms import AddNewItemForm, updateItemForm
from .serializer import CategorySerializer
from rest_framework import routers, viewsets
app_name = 'item'


urlpatterns = [
    path('add-item/', views.addNewItem, name='add-item'),
    path('search/', views.searchItem, name='search-item'),
    path('<slug>/', views.detail, name='detail'),
    path('<slug>/update-item/', views.updateItem, name='update-item'),
    path('<slug>/delete/', views.deleteItem, name='delete-item'),
    path('add-to-cart/<slug>',views.AddToCart, name='add-to-cart'),
    path('remove-from-cart/<slug>',views.RemoveFromCart, name='remove-from-cart'),
    path('<slug>/order-summary/', views.OrderSummary, name='order-summary'),
    # path('category-list/', include('rest_framework.urls', namespace='rest_framework')),
]

ecomerce/models.py
# from django.db import models
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
#
# class User(models.Model):
#     class Meta:
#         ordering = ('username',)

ecomerce/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from item.views import Item
from django.forms import ModelForm

class LoginForm(AuthenticationForm):
    # class Meta:
    #     model = User
    #     fields = ['username', 'password']
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password = forms.CharField(widget=forms.PasswordInput({
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput({
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput({
        'placeholder': 'Re-enter your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    # def clean(self):
    #     cleaned_data = super(SignUpForm, self).clean()
    #     password1 = cleaned_data.get("password")
    #     password2 = cleaned_data.get("confirm_password")
    #     if password1 != password2:
    #         self.add_error('confirm_password', "Password does not match")
    #     return cleaned_data

ecomerce/views.py
from django.shortcuts import render
from item.models import Category, Item, Order, OrderItem
from django.forms import Form
from ecomerce.forms import SignUpForm, LoginForm
from django.contrib.auth import logout
from ecomerce.serializer import UserSerializer
from rest_framework import routers, serializers, viewsets
from django.contrib.auth.models import User

# Create your views here.
from django.http import HttpResponse
def index(request):
    items = Item.objects.all()
    categories = Category.objects.all()
    return render(request, 'ecomerce/index.html', {
        'items': items,
        'categories': categories,
    })
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return ('/')
    else:
        form = SignUpForm()
    return render(request, 'ecomerce/signup.html',{
        'form': form
    })

def logout_view(request):
    item = Item.objects.all()
    categories = Category.objects.all()
    logout(request)
    return render(request, 'ecomerce/index.html', {
        'items': item,
        'categories': categories,
    })

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

ecomerce/templates/ecomerce/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load cart_item_count %}
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'ecomerce/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="https://mdbcdn.b-cdn.net/wp-content/themes/mdbootstrap4/docs-app/css/dist/mdb5/standard/core.min.css">
    <link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet">
    <link rel='stylesheet' id='roboto-subset.css-css'  href='https://mdbcdn.b-cdn.net/wp-content/themes/mdbootstrap4/docs-app/css/mdb5/fonts/roboto-subset.css?ver=3.9.0-update.5' type='text/css' media='all' />
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Hung's project</title>
</head>
<body>
         <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
             <a href="/" class="text-xl font-semibold">Hung</a>
         <div class="space-x-6">
                <a href="{% url 'item:add-item'%}" class="text-lg font-semibold hover:text-gray-500">New item</a>
                <a href="{% url 'item:search-item' %}"class="text-lg font-semibold hover:text-gray-500">Search</a>
             {% if request.user.is_authenticated %}
{#                    <a  class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>#}
{#                    <a  href="{% url 'dashboard:dashboard' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>#}
                 <button><a href="{{ item.get_order_summary_url }}"><i class="fa fa-shopping-cart text-lg"></i></a></button>
                 <span class='badge badge-warning' id="CartCount" style="margin-left: 1px">{{request.user|cart_item_count}}</span>
                    <a href="{% url 'ecomerce:logout' %}"class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log out</a>
             {% else %}
                    <a href="{% url 'ecomerce:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'ecomerce:login' %}"class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                 </div>
             {% endif %}
         </nav>
    </div>
    <div class="px-6 py-6">
         {% block content %}
         {% endblock %}
    </div>
<!-- <footer class="py-6 px-6 flex justify-between bg-gray-800">-->
<!--            <div class="w-2/3 pr-10">-->
<!--                <h3 class="mb-5 font-semibold text-gray-400">About</h3>-->

<!--                <p class="text-lg text-gray-500">Lorem ipsum bla bla bla. Lorem ipsum bla bla bla. Lorem ipsum bla bla bla.</p>-->
<!--            </div>-->

<!--            <div class="w-1/3">-->
<!--                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>-->

<!--                <ul class="space-y-2">-->
<!--                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>-->
<!--                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>-->
<!--                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>-->
<!--                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>-->
<!--                </ul>-->
<!--            </div>-->
<!--        </footer>-->
</body>
</html>

ecomerce/templates/ecomerce/index.html
{% extends 'ecomerce/base.html' %}
{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-8 text-2xl text-center">Newest items</h2>

{#        <div class="mb-6 container">#}
{#            <div class="row">#}
{#                <div class="col col-lg-2">#}
{#                    <nav class="navbar navbar-light bg-light">#}
{#                      <div class="container-fluid">#}
{#                        <form class="d-flex input-group w-auto" method="get" action="{% url 'item:search-item' %}">#}
{#                          <input#}
{#                            class="form-control rounded"#}
{#                            aria-label="Search"#}
{#                            aria-describedby="search-addon"#}
{#                            name="query" type="text" value="{{query}}" placeholder="Find your item"#}
{#                          />#}
{#                            <button class="bg-teal-400 text-white rounded-xl ">Search</button>#}
{#                        </form>#}
{#                      </div>#}
{#                    </nav>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}

        <div class="grid grid-cols-3 gap-3">
                    {% for item in items %}
                        {% load  static %}
                        {% if item.image %}
                    <div>
                        <a href="{{ item.get_absolute_url }}">
                            <div>
                                <img src="{{item.image.url }}"class="rounded-t-xl">
                            </div>
                                <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{item.name}}</h2>
                                <p class="text-gray-500">Price: {{item.price}}</p>
                            </div>
                        </a>
                    </div>
                        {% endif %}
                    {% endfor %}
        </div>
    </div>

  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
  </div>
{% endblock %}

ecomerce/templates/ecomerce/login.html
{% extends 'ecomerce/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
	<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
    </div>
{% endblock %}

ecomerce/templates/ecomerce/signup.html
{% extends 'ecomerce/base.html' %}
{% block title %}SignUp{% endblock %}
{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Signup</h1>
        <form method="POST" action=".">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1 }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Confirm Password</label>
                {{ form.password2 }}
            </div>
            {% if form.errors or form.non_field_errors %}
            <div>
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
            </div>
        </form>
</div>
{% endblock %}