core/urls.py
from django.contrib import admin
from django.urls import path
from ecomerce.views import index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from ecomerce.views import index, signup, UserViewSet
from item.serializer import CategorySerializer
from item.views import CategoryViewSet, ItemViewVset
from item.models import Category, Item

from ecomerce.views import UserViewSet
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         user = User
#         field = ('url', 'username', 'email', 'is_staff')
#
#
# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'category',CategoryViewSet, basename=Category)
router.register(r'items', ItemViewVset, basename=Item)
urlpatterns = router.urls
urlpatterns = [
                  path('', include('ecomerce.urls')),
                  path('api/', include(router.urls)),
                  path('admin/', admin.site.urls),
                  path('item/', include('item.urls')),
                  path('dashboard/', include('dashboard.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path, include
from item.views import detail
from . import views
from . forms import AddNewItemForm, updateItemForm
from .serializer import CategorySerializer
from rest_framework import routers, viewsets
app_name = 'item'


urlpatterns = [
    path('add-item/', views.addNewItem, name='add-item'),
    path('search/', views.searchItem, name='search-item'),
    path('<slug>/', views.detail, name='detail'),
    path('<slug>/update-item/', views.updateItem, name='update-item'),
    path('<slug>/delete/', views.deleteItem, name='delete-item'),
    path('add-to-cart/<slug>',views.AddToCart, name='add-to-cart'),
    path('remove-from-cart/<slug>',views.RemoveFromCart, name='remove-from-cart'),
    path('<slug>/order-summary/', views.OrderSummary, name='order-summary'),
    # path('category-list/', include('rest_framework.urls', namespace='rest_framework')),
]

item/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.urls import reverse
from rest_framework import routers, serializers, viewsets
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    price = models.FloatField(blank=True)
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    slug = models.SlugField(blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Items'

    def __str__(self):
        return self.name

    def get_object_or_404(self, pk):
        pass

    def get_absolute_url(self):
        return reverse("item:detail", kwargs={
            'slug': self.slug,
        })

    def get_add_to_cart_url(self):
        return reverse("item:add-to-cart", kwargs={
            'slug': self.slug,
        })

    def get_remove_from_cart_url(self):
        return reverse('item:remove-from-cart', kwargs={
            'slug': self.slug,
        })

    def get_order_summary_url(self):
        return reverse('item:order-summary', kwargs={
            'slug': self.slug,
        })
class OrderItem(models.Model):
    user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE)
    item = models.ForeignKey(Item, related_name='order_item', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    is_ordered = models.BooleanField(default=False)

    class Meta:
        ordering = ('item',)
        verbose_name_plural = 'Order Items'

    def __str__(self):
        return f"{self.quantity} of {self.item}"

    def get_object_or_404(self, slug):
        pass

    def get_total_item_price(self):
        return self.quantity * self.item.price

class Order(models.Model):
    user = models.ForeignKey(User, related_name='ordered_user', on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def total_price(self):
        total_price = 0
        for order_item in self.items.all():
            total_price += order_item.get_total_item_price()
        return total_price

    # def get_order_summary_url(self):
    #     return reverse('item:order-summary', kwargs={
    #         'user': self.user
    #     })

    # def get_total_item_in_cart(self):
    #     return self.ordered

item/forms.py
from django import forms
from .views import Item
class AddNewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = (
            'category',
            'name',
            'description',
            'image',
            'price',
            'slug',
        )
        widgets = {
            'category': forms.Select(attrs={
                'placeholder': 'Which category item belongs to',
                'class': 'w-full py-4 px-6 rounded-xl'
            }),
            'name': forms.TextInput(attrs={
                'placeholder': 'Item Name',
                'class': 'w-full py-4 px-6 rounded-xl'
            }),
            'description': forms.TextInput(attrs={
                'placeholder': 'Item Description',
                'class': 'w-full py-4 px-6 rounded-xl'
            }),
            'image': forms.FileInput(attrs={
                'placeholder': 'Which category item belongs to',
                'class': 'w-full py-4 px-6 rounded-xl'
            }),
            'price': forms.NumberInput(attrs={
                'placeholder': 'Which category item belongs to',
                'class': 'w-full py-4 px-6 rounded-xl'
            }),
            'slug': forms.TextInput(attrs={
                'placeholder': 'Item Slug',
                'class': 'w-full py-4 px-6 rounded-xl'
            })
        }

class updateItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = (
            'name',
            'description',
            'image',
            'price',
            'slug'
        )
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Item Name',
                'class': 'w-full py-4 px-6 rounded-xl'
            }),
            'description': forms.TextInput(attrs={
                'placeholder': 'Item Description',
                'class': 'w-full py-4 px-6 rounded-xl'
            }),
            'image': forms.FileInput(attrs={
                'placeholder': 'Which category item belongs to',
                'class': 'w-full py-4 px-6 rounded-xl'
            }),
            'price': forms.NumberInput(attrs={
                'placeholder': 'Which category item belongs to',
                'class': 'w-full py-4 px-6 rounded-xl'
            }),
            'slug': forms.TextInput(attrs={
                'placeholder': 'Item Slug',
                'class': 'w-full py-4 px-6 rounded-xl'
            })
        }

item/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from .models import Item, Category, OrderItem, Order
from django.db.models import Q
from .forms import AddNewItemForm, updateItemForm
from django.contrib.auth.decorators import login_required
from rest_framework import routers, serializers, viewsets, generics
from .serializer import CategorySerializer, ItemSerializer
from django.contrib import messages
from django.contrib.auth.admin import User
from django.utils import timezone
# Create your views here.

def searchItem(request):
    items = Item.objects.filter(is_sold=False)
    query = request.GET.get('query', '')
    categories = Category.objects.all()
    category_id = request.GET.get('category',0)
    if category_id:
        items = items.filter(category_id=category_id)
    if query is not None:
        items = items.filter(Q(name__icontains=query)) | items.filter(Q(description__icontains=query))
    return render(request, 'item/search.html',{
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': category_id,
    })

def detail(request, slug):
    item = get_object_or_404(Item,slug=slug)
    return render(request, 'item/detail.html', {
        'item': item
    })

@login_required
def addNewItem(request):
    if request.method == 'POST':
        form = AddNewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user # Store user who create item
            item.save() # Create item
            return redirect('item:detail', slug=item.slug)
    else:
        form = AddNewItemForm()
    return render(request, 'item/add-item.html', {
        'form': form,
        'title': 'New Item',
    })

@login_required()
def deleteItem(request, slug):
    item = get_object_or_404(Item, slug=slug, created_by=request.user)
    item.delete()
    return render(request, 'ecomerce/index.html')

@login_required()
def updateItem(request, slug):
    item = get_object_or_404(Item, slug=slug, created_by=request.user)
    if request.method == 'POST':
        form = updateItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save() # save update data
            return redirect('item:detail',slug=item.slug)
    else:
        form = updateItemForm(instance=item)
    return render(request,'item/updateitem.html', {
        'form': form,
        'title': 'Update Item Info',
    })
class CategoryViewSet(viewsets.ModelViewSet):
        queryset = Category.objects.all()
        serializer_class = CategorySerializer

class ItemViewVset(viewsets.ModelViewSet):
    queryset = Item.objects.all().select_related('category')
    serializer_class = ItemSerializer
    lookup_field = 'category'


def Cart_Item_Count(request, user):
    if user.is_authenticated:
        order_qs = Order.objects.filter(user=user, ordered=False)
        if order_qs.exists():
            return order_qs[0].items.count()
    return render(request,'ecomerce/base.html',{
        'order': order_qs,
    })


def OrderSummary(request, slug):
    order = Order.objects.get(user=request.user)
    return render(request, 'item/ordersummary.html', {
        'order': order,
        })

@login_required()
def AddToCart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item = item,
        user = request.user,
        is_ordered=False,
    )
    order_queue = Order.objects.filter(user=request.user, ordered=False)
    if order_queue.exists():
        order = order_queue[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "The item in cart was updated")
            return redirect('item:order-summary', slug=slug)
        else:
            order.items.add(order_item)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
    return redirect('item:detail', slug=slug)

@login_required()
def RemoveFromCart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists(): #check if order is exist
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists(): #check if order item is exist or not
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                is_ordered=False,
            )[0]
            if order_item.quantity > 1 :
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
                messages.info(request, 'The item in cart was updated')
                # order_item.delete()
            return redirect('item:order-summary', slug=slug)
        else:
            return redirect("item:detail", slug=slug)
    else:
        return redirect("item:detail", slug=slug)

item/templates/item/add-item.html
{% extends 'ecomerce/base.html' %}
{% block title %}Add New Item{% endblock %}
{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl" align="center">Add New Item</h1>
        <form method="POST" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="mb-3">
               {{ form.as_p }}
            </div>
            {% if form.errors or form.non_field_errors %}
            <div>
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
            </div>
        </form>
</div>
{% endblock %}

item/templates/item/additem.html
{% extends 'ecomerce/base.html' %}
{% block title %}Add New Item{% endblock %}
{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl" align="center">Add New Item</h1>
        <form method="POST" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="mb-3">
               {{ form.as_p }}
            </div>
            {% if form.errors or form.non_field_errors %}
            <div>
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
            </div>
        </form>
</div>
{% endblock %}

item/templates/item/detail.html
{% extends 'ecomerce/base.html' %}

{% block title %}
{{ item.name }}
{% endblock %}

{% block content %}
    {% if item.image %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{item.image.url}}" class="rounded-xl">
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-500"><strong>Category: </strong>{{ item.category }}</p
        <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}</p>
        <p class="text-gray-500"><strong>Seller: </strong>{{ item.created_by.username }}</p>

        {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ item.description }}
            </p>
        {% endif %}
    
{#        {% if request.user == item.created_by %}#}
            <a href="{{ item.get_add_to_cart_url }}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Add To Cart</a>
            <a href="{{ item.get_remove_from_cart_url }}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-teal-700">Remove From Cart</a>
            <a href="{% url 'item:update-item' item.slug %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Update Item</a>
            <a href="{% url 'item:delete-item' item.slug %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-teal-700">Delete</a>
{#        {% endif %}#}
    {% endif %}
    </div>
</div>

{% endblock %}

item/templates/item/ordersummary.html
{% extends 'ecomerce/base.html' %}
{% block title %}Order Summary{% endblock %}

{% block content %}
    <div class="container">
    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in order.items.all %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ order_item.item.name }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'item:remove-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'item:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>${{ order_item.get_total_item_price }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    </div>

{% endblock %}

item/templates/item/search.html
{% extends 'ecomerce/base.html' %}

{% block title %}Items{% endblock %}

{% block content %}
    <div class="nav pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'item:search-item' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{query}}" placeholder="Find your item">
                <div class="text-center">
                    <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
                </div>

            </form>
            <hr class="my-6">
            <p class="font-semibold text-center">Categories</p>
            <ul style="padding-left: 20px">
                {% for category in categories %}
                    <li style="list-style-type: square">
                        {% if category.id == category.id %}
                        <a  href="{% url 'item:search-item'%}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                        {% endif %}
                {% endfor %}
                    </li>
            </ul>
            <hr class="my-6">
            <div class="text-center">
            {%  if category_id != 0 %}
                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl"><a href="{% url 'item:search-item'%}">Clear Filter</a></button>
            {% endif %}
        </div>
        </div>
        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detail' item.slug %}">
{#                            {% if image.url %}#}
                            <div>
                                <img src="{{ item.image.url }}" class="rounded-t-xl">
                            </div>
{#                            {% endif %}#}
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

item/templates/item/updateitem.html
{% extends 'ecomerce/base.html' %}
{% block title %}Update Item{% endblock %}
{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl" align="center">Add New Item</h1>
        <form method="POST" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="mb-3">
               {{ form.as_p }}
            </div>
            {% if form.errors or form.non_field_errors %}
            <div>
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
            </div>
        </form>
</div>
{% endblock %}