core/urls.py
from django.contrib import admin
from django.urls import path
from ecomerce.views import index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from ecomerce.views import index, signup, UserViewSet
from item.serializer import CategorySerializer
from item.views import CategoryViewSet, ItemViewVset
from item.models import Category, Item

from ecomerce.views import UserViewSet
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         user = User
#         field = ('url', 'username', 'email', 'is_staff')
#
#
# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'category',CategoryViewSet, basename=Category)
router.register(r'items', ItemViewVset, basename=Item)
urlpatterns = router.urls
urlpatterns = [
                  path('', include('ecomerce.urls')),
                  path('api/', include(router.urls)),
                  path('admin/', admin.site.urls),
                  path('item/', include('item.urls')),
                  path('dashboard/', include('dashboard.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
from dashboard.views import index

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='dashboard')
]

item/urls.py
from django.urls import path, include
from item.views import detail
from . import views
from . forms import AddNewItemForm, updateItemForm
from .serializer import CategorySerializer
from rest_framework import routers, viewsets
app_name = 'item'


urlpatterns = [
    path('add-item/', views.addNewItem, name='add-item'),
    path('search/', views.searchItem, name='search-item'),
    path('<slug>/', views.detail, name='detail'),
    path('<slug>/update-item/', views.updateItem, name='update-item'),
    path('<slug>/delete/', views.deleteItem, name='delete-item'),
    path('add-to-cart/<slug>',views.AddToCart, name='add-to-cart'),
    path('remove-from-cart/<slug>',views.RemoveFromCart, name='remove-from-cart'),
    path('<slug>/order-summary/', views.OrderSummary, name='order-summary'),
    # path('category-list/', include('rest_framework.urls', namespace='rest_framework')),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from item.models import Item, Category
# Create your views here.
@login_required()
def index(request):
    items = Item.objects.all()
    categories = Category.objects.all()
    return render(request, 'dashboard/index.html',{
        'items': items,
        'categories': categories,
    })

dashboard/templates/dashboard/index.html
{% extends 'ecomerce/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">My items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}